### ISSUE TITLE
Incorrect punctuation in certain AR translations

### ISSUE THREAD

**Issue by omarsafwany** [forzagreen/n2words#100]
First of all, Awesome work. 🔥 
I checked a number of different libraries and that's the most accurate one so hats off.

Problem
When translating certain arabic numbers, there seems to be a certain issue with spaces and `و`.

Input
`n2words(820, {lang: 'ar'})`

Expected `"ثمانمائة و عشرون"`
Actual `"ثمانمائةعشرون"`

Input
`n2words(810, {lang: 'ar'})`
Expected == Actual which is `"ثمانمائة و عشرة"`

Input
`n2words(823, {lang: 'ar'})`
Expected == Actual which is `"ثمانمائة و ثلاثة و عشرون"`

The rest `833, 843 & 853` are of same pattern

But `863, 873, 883 & 893` start the response with `ثمانمائةثلاثة`
so there is a missing space after `ثمانمائة` and missing `و` to be consistent with the rest.

Also regarding the number `200` which is a special case, the missing space makes the output incorrect
Input: `287`
Expected: `"مئتان و سبعة و ثمانون"`
Actual: `"مئتانسبعة و ثمانون"`

**Comment by forzagreen** [comment]
@omarsafwany thank you for you encouragements and for reporting the issue.
Indeed, I am aware of issues in Arabic, and I really want to fix them all. It's just a matter of time and organisation.
Meanwhile, I came across this library [nArabicWords](https://github.com/MohsenAlyafei/nArabicWords) that imitates n2words, but only for Arabic. It seems to support it very well. I hope soon we'll incorporate the same options in n2words.

**Comment by forzagreen** [comment]
Hi @omarsafwany , we have just released a new version [n2words/v1.20.0](https://github.com/forzagreen/n2words/releases/tag/v1.20.0)  that fixes this issue and others in Arabic.
Feel free to test and let me know if you see other issues.
Thanks
