### ISSUE TITLE
Wiki - config option is wrong and missing explanation

### ISSUE THREAD

**Issue by x-m-el** [forzagreen/n2words#119]
at https://github.com/forzagreen/n2words/wiki/Language-options#nl
the word `noHundredsPair` should be `noHundredPairs` to fit the config variable of the actual code.

An example of what these do could also be useful. 

Here's an example you could add:

- includeOptionalAnd (default false):
  include "and" between numbers. E.g. 101 becomes "honderdeneen" instead of "hondereen". 1010 becomes "duizend en tien" instead of "duizend tien".
- noHundredPairs (default false):
 Do not pair cardinal values per hundreds. E.g. 1.1111 becomes "een komma duizend honderdenelf" instead of "een komma elfhonderd en elf"

**Comment by TylerVigario** [comment]
Thanks for pointing that out and for your suggestions. I'll get that updated shortly.

**Comment by TylerVigario** [comment]
@x-m-el Wiki has been updated. You can check it out [here](https://github.com/forzagreen/n2words/wiki/Language-options). Thanks again!
