### ISSUE TITLE
Cannot import language specific file in Typescript project

### ISSUE THREAD

**Issue by killianhuyghe** [forzagreen/n2words#122]
Hello, I would like to import language specific files in typescript and have the following issue:
```
Cannot find module 'n2words/i18n/fr.js' or its corresponding type declarations.ts(2307)
```

I have looked at the Typescript help page and did try various tsconfig options without success.

I have created a minimal repro case for my setup (Typescript/React) in codesandbox:
https://codesandbox.io/s/jolly-grass-lvpfwh?file=/src/App.tsx

Note that I also see an error with the regular `import n2words from "n2words";`, but that one I can workaround with `// @ts-ignore`.

**Comment by TylerVigario** [comment]
@killianhuyghe Please make the following changes to your project.

- Update to the latest **n2words** (`1.16.4` as of writing)
- Drop **TypeScript** `4.4.2` from `devDependencies` (you already have the latest version in your `dependencies`).
- Add `"moduleResolution": "nodenext"` to your _tsconfig.json_
