### ISSUE TITLE
Option to capitalize significant words

### ISSUE THREAD

**Issue by ASutrick** [forzagreen/n2words#123]
For example, 122 is 'one hundred and twenty-two'. Could we get an option to have it return 'One Hundred and Twenty-Two'?

**Comment by forzagreen** [comment]
Hi @ASutrick , thank you for reporting. You are looking to have the result in **title case**. In my opinion, this is out of the scope of n2words, and should be done outside. You can easily find javascript functions that convert strings to title case.
