### ISSUE TITLE
Triple zero output for numbers ending with double zero

### ISSUE THREAD

**Issue by florushj** [forzagreen/n2words#124]
Using the default config for multiple languages (NL, EN, DE) (I did not test all) makes numbers ending with double zeros output to a value with triple zeros. 

Faulty tests in EN:

- 100.00 should output: "one hundred point zero zero". But outputs: "one hundred point zero zero **zero**" 
- 1234.00 should output: "one thousand two hundred and thirty-four point zero zero". But outputs: "one thousand two hundred and thirty-four point zero zero **zero**" 

It only happens for numbers ending with double zero. Correct tests in EN:

- 102.02 should output: "one hundred and two point zero two" and it does so correctly.

**Comment by TylerVigario** [comment]
Thank you for reporting this. I'll take a look later and hopefully resolve this today.

**Comment by TylerVigario** [comment]
I can see how https://github.com/forzagreen/n2words/blame/ab74750586e77b63ac3b1ec073c74495c916fa2d/lib/classes/AbstractLanguage.js#L87 would create a 0 from the remaining output ("") in these events. I am working on a fix, but it may take until this weekend.

**Comment by TylerVigario** [comment]
Merged in #125 will put out a release later today. Thanks again for reporting!

**Comment by florushj** [comment]
Had a quick look at the changes, and it seems like this would fix it indeed. Will test and check out the new code once it is released. Thanks for all your hard work and rapid response!

**Comment by forzagreen** [comment]
Released in [v1.17.0](https://github.com/forzagreen/n2words/releases/tag/v1.17.0) 🎉 
Thank you @florushj  for reporting, and thank you @TylerVigario  for fixing !
