### ISSUE TITLE
Error: Cannot find module 'n2words' or its corresponding type declarations

### ISSUE THREAD

**Issue by michalgrzyska** [forzagreen/n2words#127]
Thing happens when writing Firebase Functions. I installed n2words with `npm i` and have:

![image](https://github.com/forzagreen/n2words/assets/61694056/14155226-c504-477e-b195-d557acad3983)

When I try with `// @ts-ignore` it compiles, but functions return:

```
Failed to initialize and load triggers. This shouldn't happen: require() of ES Module [mypath]\functions\node_modules\n2words\lib\n2words.js from [mypath]\functions\lib\tax-computing\money-to-words.js not supported.
Instead change the require of n2words.js in [mypath]\functions\lib\tax-computing\money-to-words.js to a dynamic import() which is available in all CommonJS modules.
```

Any ideas how to fix that?

**Comment by TylerVigario** [comment]
@michalgrzyska Have you tried using [CommonJS Dynamic Import](https://github.com/forzagreen/n2words/wiki/TypeScript-support#commonjs)?

**Comment by TylerVigario** [comment]
I will close this issue, but feel free to comment further or open a new one.

**Comment by michalgrzyska** [comment]
Sorry for my delay. Thanks for the reply - I tried to use n2words in the way that is shown in link you sent:

```
import('n2words/i18n/en.js').then(({default: n2words}) => {
    console.log(n2words(100)) // "one hundred"
})
```

I converted it a bit to have a possibility of getting string as a result:

```
export async function moneyToWords(money: number): Promise<string> {
  const n2wordsModule = await import("n2words/i18n/en.js");
  const { default: n2words } = n2wordsModule;
  return n2words(money);
}
```

But still I get:
![image](https://github.com/forzagreen/n2words/assets/61694056/9f77c56c-8219-42f8-ae08-1f17a13b1001)

VSCode shows only:
![image](https://github.com/forzagreen/n2words/assets/61694056/6852a897-d650-43ba-925f-238d2ed87ca2)

And my ts.config has 
```
    "module": "commonjs",
    "target": "es2022",
```

I know this is strange, but Firebase Functions are very tricky and for some reason limited in some areas. I tried to set ES6 & NodeNext, but then something is not compiling in `node_modules` in `long` module 😒

**Comment by SmashinFries** [comment]
You can import it like this (ES6/ES2015):

``` ts
import n2words from 'n2words/lib/i18n/en'
```

**Comment by michalgrzyska** [comment]
> You can import it like this (ES6/ES2015):
> 
> ```ts
> import n2words from 'n2words/lib/i18n/en'
> ```

I tried but it throws this:

```
Error [ERR_PACKAGE_PATH_NOT_EXPORTED]: Package subpath './lib/i18n/en' is not defined by "exports" in myprojectpath\functions\node_modules\n2words\package.json
    at new NodeError (node:internal/errors:387:5)
    at throwExportsNotFound (node:internal/modules/esm/resolve:365:9)
    at packageExportsResolve (node:internal/modules/esm/resolve:649:3)
    at resolveExports (node:internal/modules/cjs/loader:522:36)
    at Function.Module._findPath (node:internal/modules/cjs/loader:562:31)
    at Function.Module._resolveFilename (node:internal/modules/cjs/loader:971:27)
    at Function.Module._load (node:internal/modules/cjs/loader:833:27)
    at Module.require (node:internal/modules/cjs/loader:1057:19)
    at require (node:internal/modules/cjs/helpers:103:18)
    at Object.<anonymous> (myprojectpath\functions\lib\generate-invoice\money-to-words.js:4:14)
```

**Comment by TylerVigario** [comment]
The correct import would be `import n2words from 'n2words/i18n/en'`; however, this won't work in a CommonJS project.

@michalgrzyska Could you share a minimal repo that highlights the issue?

**Comment by michalgrzyska** [comment]
@TylerVigario sure. Here is an example as my public repo: https://github.com/michalgrzyska/n2words-error-sample

**Comment by TylerVigario** [comment]
@michalgrzyska Thank you. I did a quick search and found that Firebase does support ESM. I'll try making it work with this repo and see what I find.

**Comment by michalgrzyska** [comment]
Thanks a lot. There may probably be some problem with my different packages but I'll try to find substitutes.

**Comment by michalgrzyska** [comment]
@TylerVigario was it possible to make anything working?

**Comment by TylerVigario** [comment]
@michalgrzyska I know this is a late reply, and after the promise of figuring it out, I must apologize. Unfortunately, I won't be able to sort this out. As this is an issue outside of this package, I will close it for now. Like before, please revive this thread if something relevant pops up in the future.
