### ISSUE TITLE
Bug in AbstractLanguage for decimalNumbers with zero at the end

### ISSUE THREAD

**Issue by PattaBov** [forzagreen/n2words#133]
Thank you for your work, this library is a huge help as we convert numbers to text in several languages for our project.

I need to point out a bug though. 

When we want to convert some value with two decimals finishing with zero, like "12.50", we expect a string value of "twelve point fifty" but we actually get "twelve point zero fifty".

It comes from the decimalToCardinal function in AbstractLanguage.js:
```javascript 
// Loop through array (from the end) adding leading zeros to output array
chars.forEach(char => {
    if (char === '0') {
        words.push(this.zero);
    } else {
        allZero = false;
    }
});
```

I think it misses a break after
```javascript
allZero = false;
```

Other small things, our german colleagues told us that komma in german takes a capital K so "12.50" => "zwölf Komma fünfzig"

Thank you for reading

**Comment by forzagreen** [comment]
Hi @PattaBov ,
Thanks for reporting.
Could you please provide the version you are using? 
I haven't encountered these issues with the latest version (1.19.0):

```
> n2words(12.50)
'twelve point five'
> n2words(12.50, {lang: "de"})
'zwölf komma fünf'
```

In regards to representing the result "12.50" as "twelve point five", I believe we could offer an option to display it as "twelve point fifty" instead.

**Comment by TylerVigario** [comment]
> I think it misses a break after
> 
> ```js
> allZero = false;
> ```

@PattaBov Good catch! I'll get this updated ASAP

**Comment by PattaBov** [comment]
Hi, thanks for the update. We were using the version 1.17.0.
I'm gonna update the package and test it.

**Comment by PattaBov** [comment]
That seems perfect to me, thank you for your quick reaction!

**Comment by PattaBov** [comment]
> Other small things, our german colleagues told us that komma in german takes a capital K so "12.50" => "zwölf Komma fünfzig"

My testing team just pointed me out that the output still is "komma" instead of "Komma", I'm sorry about that, it can

**Comment by TylerVigario** [comment]
@PattaBov I only manage the project structure and keep it up-to-date with the latest JavaScript standards. Maybe @forzagreen can chime in with insight into languages, regions, and words.

However, I have made each language as flexible as possible so you can specify a different `seperatorWord`. See below for an example.

```js
import n2words from 'n2words/i18n/de.js'

n2words(100, {
  seperatorWord: 'Komma'
})
```

**Comment by forzagreen** [comment]
Thank you, @TylerVigario , for the resolution.
@PattaBov , I suggest closing this issue and opening a new one.

**Comment by PattaBov** [comment]
Thank you, 
Tyler's suggestion is actually enough. I'm sorry I didn't think about that.
