### ISSUE TITLE
Improve project structure & build system

### ISSUE THREAD

**Issue by MeekLogic** [forzagreen/n2words#16]
I believe it would be beneficial to remove the build system from this library. This library needs more code to actually work for the end user thus it probably shouldn't be packaged up in this way.

Is there something that I am missing?

**Comment by forzagreen** [comment]
The priority is to have the library work both in Node.js and in browsers.
Currently I build with Grunt and Babel.
If you have a better proposition feel free to open a PR. I can help on it. Do you have good docs/tutorials/resources on the topic ?

**Comment by MeekLogic** [comment]
I will absolutely send in a PR when I figure out which direction to take it.

My goal with this issue would be to remove the build system from at least the source file. Instead of adding all loader support in the source file we would build compatible libraries for different loaders.

Very much like [Popper.js](https://github.com/popperjs/popper-core)

**Comment by MeekLogic** [comment]
Added PR #19
