### ISSUE TITLE
capitalize in German

### ISSUE THREAD

**Issue by ludans** [forzagreen/n2words#2]
hello,
great module - I'll use it for RosaeNLG
a small bug in German: millionen etc. must be capitalized

`zwei Millionen sechshundertvierundfünfzigtausendfünfhundertvierundsechzig`
and not
`zwei millionen sechshundertvierundfünfzigtausendfünfhundertvierundsechzig`

would it be possible to correct it? so that I could remove my patch

**Comment by forzagreen** [comment]
Fixed in `v1.3.2`

**Comment by ludans** [comment]
thanks!
