### ISSUE TITLE
NPM package does not include ES Modules (aka src/)

### ISSUE THREAD

**Issue by MeekLogic** [forzagreen/n2words#21]
Is there a reason why you want to exclude the source modules from NPM? That means there is no way to consume the source modules when installing via NPM.

**Comment by forzagreen** [comment]
I thought it needs only the files inside dist/ 
I will fix it.

**Comment by forzagreen** [comment]
n2words@1.6.1 released

**Comment by MeekLogic** [comment]
The dist folder contains Babel compiled and polyfilled bundle.

It's my desire to be able to consume the source modules as-is and compile (or not compile) depending on my specific application. I greatly appreciate your willingness to restructure and push forward towards that goal.
