### ISSUE TITLE
Spanish money

### ISSUE THREAD

**Issue by llermaly** [forzagreen/n2words#47]
Hello ,

Is there any way to customize the library to have support in some money cases like : 

$1.000.000 should be "un millon **de** pesos"

but translates into  "un millón pesos"

same with 

$1.000.001 should be "un millón **un** peso"

Translates into "un millón uno peso"

thanks!

**Comment by forzagreen** [comment]
Today, the library does not support currencies. We may add it in the future.
Thanks for the suggestion.

**Comment by llermaly** [comment]
Hello, I applied 2 functions that fixes my problems in case somebody has the same problem as me.

Assuming you put "de pesos" after the numer in words: 

```
//millions definition
  const isMillion = (num) => (Number.isInteger(num / 1000000) ? ' de' : '');

// uno vs un
  const isUno = (string) => string && string.replace(/uno/g, 'un');
```

**Comment by forzagreen** [comment]
Currencies are not supported.
The feature may be added later.
