### ISSUE TITLE
Uncaught ReferenceError: n2words is not defined

### ISSUE THREAD

**Issue by Toso82** [forzagreen/n2words#50]
I use:

```ps
Angular CLI: 12.0.5
Node: 16.3.0
Package Manager: npm 7.18.1
OS: win32 x64

Angular: 12.0.5
... animations, cdk, cli, common, compiler, compiler-cli, core
... forms, localize, material, material-moment-adapter
... platform-browser, platform-browser-dynamic, router

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1200.5
@angular-devkit/build-angular   12.0.5
@angular-devkit/core            12.0.5
@angular-devkit/schematics      12.0.5
@angular/flex-layout            12.0.0-beta.34
@schematics/angular             12.0.5
rxjs                            6.6.7
typescript                      4.2.4

```

```ts
import n2words from 'n2words';

n2words(valSplit[0], {lang: 'it'})
```

**Comment by forzagreen** [comment]
Could you please give more details on how to reproduce this bug ?

**Comment by Toso82** [comment]
```powershell
npm -g install @angular/cli
ng new ng2word
npm install ng2word
npm i --save-dev @types/n2words
```


I import in  app.component.ts

import n2words from 'n2words';

"No declaration file was found for the 'n2words' module. A 'e: /Angular/ng2word/node_modules/n2words/dist/n2words.js' is implicitly assigned an 'any' type.
   Try `npm i --save-dev @ types / n2words` if it exists or add a new declaration file with extension d.ts containing` declare module 'n2words'; `ts (7016)"

Miss types of n2words. So i create one:

n2words.d.ts

```ts
declare module 'n2words'; 
```

in app.components.ts i have this:

```ts
import { Component } from '@angular/core';
import n2words from 'n2words';

@Component({
  selector: 'app-root',
  templateUrl: './app.component.html',
  styleUrls: ['./app.component.scss']
})
export class AppComponent {

  title = 'ng2word';
   constructor() {
    console.log(n2words('10', {lang: 'it'}))  
    
  }
}
```

```powershell
ng serve
```

Console log:
```
undefined
```

**Comment by forzagreen** [comment]
You didn't install n2words.
Try `npm install n2words` (instead of `npm install ng2word`)

**Comment by Toso82** [comment]
I wrong to write 

```json

"dependencies": {
    "@angular/animations": "~12.1.0",
    "@angular/common": "~12.1.0",
    "@angular/compiler": "~12.1.0",
    "@angular/core": "~12.1.0",
    "@angular/forms": "~12.1.0",
    "@angular/platform-browser": "~12.1.0",
    "@angular/platform-browser-dynamic": "~12.1.0",
    "@angular/router": "~12.1.0",
    "n2words": "^1.9.0",
    "rxjs": "~6.6.0",
    "tslib": "^2.2.0",
    "zone.js": "~0.11.4"
  },

```

**Comment by forzagreen** [comment]
Try with:
```ts
// @ts-ignore
import n2words from 'n2words';
```
Check this example:
https://github.com/AnthonyNahas/ngx-num-to-words/blob/d4a6a227ce09dbe24f79eba740f8017ada9e589e/projects/ngx-num-to-words/src/lib/ngx-num-to-words.service.ts#L2-L3

**Comment by Toso82** [comment]
@forzagreen  Change nothing just ignore ts-lint error but not compile correct in angular.  If you try you see.

**Comment by forzagreen** [comment]
I am able to reproduce the bug.
I can see n2words in Sources, but still can't call it:
![image](https://user-images.githubusercontent.com/8544289/123996336-87848a00-d9cf-11eb-8f05-e3d48fe2e00d.png)

**Comment by forzagreen** [comment]
@Toso82  Can you try passing a number instead of a string ?
i.e. `console.log(n2words(10, {lang: 'it'}))`  , instead of `"10"`

**Comment by Toso82** [comment]
@forzagreen  This is the type number work i must to cast all but it is ok. It is strange old version work well

**Comment by forzagreen** [comment]
@Toso82 , Thanks for reporting.
I see the issue:
https://github.com/forzagreen/n2words/blob/0f73917579ad89c31ce4220ead6a6086ccb3feac/lib/classes/N2WordsAbs.mjs#L26
and:
https://github.com/forzagreen/n2words/blob/0f73917579ad89c31ce4220ead6a6086ccb3feac/lib/classes/N2WordsAbs.mjs#L46-L48

We have either to accept strings, or to throw an explicit error.
