### ISSUE TITLE
exclude some languages

### ISSUE THREAD

**Issue by jordankkk** [forzagreen/n2words#53]
Can we exclude some languages to reduce the bundle size?

Thanks

**Comment by forzagreen** [comment]
It's not possible today. See discussion in https://github.com/forzagreen/n2words/pull/40 for more details

**Comment by TylerVigario** [comment]
Depends if you are using CommonJS or ECMAScript Modules.

If you are using ESM it's as simple as [including the desired language file(s)](https://github.com/forzagreen/n2words/blob/master/lib/n2words_EN.mjs) and calling the `.floatToCardinal()` method.

```js
import n2words from 'n2words/lib/i18n/EN.mjs';

n2words.floatToCardinal(20);
```

**Comment by TylerVigario** [comment]
This should be closed IMHO
