### ISSUE TITLE
Errors in Serbian

### ISSUE THREAD

**Issue by lagavuliner** [forzagreen/n2words#60]
In the Serbian version:

- "četristo" should be "čet**i**risto" (400)
- Serbian uses the [long scale](https://www.blic.rs/slobodno-vreme/vesti/milijarda-ili-bilion-kvadrilion-ili-bilijarda-muce-vas-veliki-brojevi-ovo-treba-da/qxqtfdt), i.e.

- 10^9 is "milijarda, milijarde, milijarda"
- 10^12 is "bilion, biliona, biliona"
- 10^15 is "bilijarda, bilijarde, bilijarda"
- 10^18 is "trilion, triliona, triliona"
- 10^21 is "trilijarda, trilijarde, trilijarda"
- 10^24 is "kvadrilion, kvadriliona, kvadriliona"
- 10^27 is "kvadrilijarda, kvadrilijarde, kvadrilijarda" and
- 10^30 is "kvintilion, kvintiliona, kvintiliona"

**Comment by forzagreen** [comment]
Fixed in https://github.com/forzagreen/n2words/issues/61, released in [v1.11.0](https://github.com/forzagreen/n2words/releases/tag/v1.11.0)
