### ISSUE TITLE
Czech translation: hundreds

### ISSUE THREAD

**Issue by Mr-Hyde** [forzagreen/n2words#70]
Hey!
Thank you for this library, it's great, but could you please fix the Czech translation? 
the hundreds are actually 2 separated words:
this.hundreds = {
      1: 'sto',
      2: 'dvě stě',
      3: 'tři sta',
      4: 'čtyři sta',
      5: 'pět set',
      6: 'šest set',
      7: 'sedm set',
      8: 'osm set',
      9: 'devět set'
    };
Best regards!

**Comment by forzagreen** [comment]
Thank you @Mr-Hyde  for reporting.
Could you please check the fix in this PR https://github.com/forzagreen/n2words/pull/71 ?
