### ISSUE TITLE
Can we easy migrate PR from js-written-number

### ISSUE THREAD

**Issue by sytolk** [forzagreen/n2words#78]
I have provide this PR for Bulgarian language support but its appears that js-written-number is not supported. Can I easy migrate it to this project https://github.com/yamadapc/js-written-number/pull/96/files

**Comment by forzagreen** [comment]
Done

**Comment by sytolk** [comment]
Thanks @forzagreen this means that js-written-number project is still alive ?

**Comment by forzagreen** [comment]
Not really. I'll try to merge some pull requests in js-written-number, but I don't have permissions to release a new version.
Prefer using n2words.

**Comment by sytolk** [comment]
ok I will try to provide PR for Bulgarian language support in n2words project.
